### ISSUE TITLE
Error: No such container: query_frontend-parm

### ISSUE THREAD

**Issue by halo-geng** [Thesys-lab/parity-models#18]
Hi,
I ran into some problems when trying **Single-machine setup** of the **Latency experiments**.
I have finished **./setup.sh** and **./setup.sh continue**.

Quetion 1:
There is a `"host" network_mode is incompatible with port_bindings` problem when running **run_exp.py**.
According to  [Clipper Issues #642](https://github.com/ucbrise/clipper/issues/642), I commented out `"network_mode": "host"` and uncommented `"network": self.docker_network` on line 95 of **parm_docker_container_manager.py**.
I don't know if it is correct, but it worked. I'm curious why `"network_mode": "host"` instead of `"network": self.docker_network` is used in the source code.

Question 2:
It keeps printing `[clipper_admin.py:124] Clipper still initializing.` when running **run_exp.py**. 
I checked and found that  the container named **query_frontend-parm** exited immediately after it was created and run, which made it impossible to establish a connection with this container.
And the docker log shows `/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version CXXABI_1.3.11 not found`, but what can be confirmed by inspection is that CXXABI_1.3.11 is included in libstdc++.so.6 in my system environment.
Can I ask if you have encountered such a problem and how did you solve it?

**Comment by jackkosaian** [comment]
Thank you for your interest in our work!

Unfortunately, I don't remember why I used `"network_mode": "host"`, but if using `docker_network` works for you instead, perhaps that is OK.

Regarding your second question, could you please specify the the platform on which you are running (e.g., OS, hardware, etc.)? I just tried the instructions again today on Ubuntu 16.04 on an AWS c5.9xlarge instance and they worked for me.
