### ISSUE TITLE
ResNet152 on Cifar100 seems missed

### ISSUE THREAD

**Issue by neolinsu** [Thesys-lab/parity-models#4]
Hi,
  I can not run 
```Shell
python3 train_config.py config/cifar100.json save/
```
by receiving message like:
```Shell
cifar100 resnet152 2 mse add sub
Traceback (most recent call last):
  File "train_config.py", line 272, in <module>
    dataset, base_type)
  File "train_config.py", line 233, in get_parity_model
    raise Exception("Unrecognized parity_model_type '{}'".format(parity_model_type))
Exception: Unrecognized parity_model_type 'resnet152'
```

**Comment by jackkosaian** [comment]
Thanks for raising this issue!

I've added the necessary fix for this in the latest commit. I also fixed a formatting error with the CIFAR-100 ResNet-152 base model file and have put this in the parity-models s3 bucket, so you will need to download this new file using `./download_base_models.sh`.

Could you please try pulling the latest version of the code and downloading this new model file?
