### ISSUE TITLE
Downloading models from AWS returns "fatal error: Unable to locate credentials"

### ISSUE THREAD

**Issue by Eric-mingjie** [Thesys-lab/parity-models#5]
When I try the command "aws s3 cp s3://parity-models/base-models/ base_model_trained_files --recursive", it returns "fatal error: Unable to locate credentials".  

Is there some access issue that I am not aware of here?

**Comment by jackkosaian** [comment]
Using the AWS CLI, even to just download public datasets, requires that one have an AWS account and that the CLI is configured with your account information using [aws configure](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).

Have you configured an AWS account for your CLI installation? If this is a barrier for you, I can try to get you the files another way.

**Comment by Eric-mingjie** [comment]
Thanks! I have solved my issue.
